server:
  port: 8080

spring:
  application:
    name: metal-store
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update

supabase:
  url: ${SUPABASE_URL:}
  publishable-key: ${SUPABASE_PUBLISHABLE_KEY:}
  secret-key: ${SUPABASE_SECRET_KEY:}
