server:
  port: 8080

spring:
  application:
    name: metal-store
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
