-- Add created_at and updated_at columns to all tables that extend BaseEntity.
-- Existing rows get NOW() as their audit timestamp.
-- Safe to re-run (all ADD COLUMN use IF NOT EXISTS).

ALTER TABLE catalog_families     ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE catalog_profiles     ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE catalog_items        ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE catalog_item_types   ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE inventory_items      ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE clients              ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE quotes               ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE quote_lines          ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE price_list           ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE invoices             ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE invoice_lines        ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE tenants              ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();
ALTER TABLE users                ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(), ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW();

-- Remove defaults so only JPA Auditing sets these columns going forward.
ALTER TABLE catalog_families     ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE catalog_profiles     ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE catalog_items        ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE catalog_item_types   ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE inventory_items      ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE clients              ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE quotes               ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE quote_lines          ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE price_list           ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE invoices             ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE invoice_lines        ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE tenants              ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE users                ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN updated_at DROP DEFAULT;
